
---
- name: Local Play
  connection: local
  hosts: all
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
          - zsh
          - vim
          - tmux
          - autojump
          - build-essential
          - pkg-config
          - clang
          - git
          - cmake
          - python3
          - python3-sphinx 	
          - python3-packaging
          - libcairo2-dev
          - i3
          - i3-wm
          - libxcb1-dev
          - libxcb-util0-dev
          - libxcb-randr0-dev
          - libxcb-composite0-dev
          - python3-xcbgen
          - xcb-proto
          - libxcb-image0-dev
          - libxcb-ewmh-dev
          - libxcb-icccm4-dev
          - libxcb-xkb-dev
          - libxcb-xkb-dev 
          - libxcb-xrm-dev 
          - libxcb-cursor-dev 
          - libasound2-dev 
          - libpulse-dev 
          - libjsoncpp-dev 
          - libmpdclient-dev 
          - libcurl4-openssl-dev 
          - libnl-genl-3-dev
          - python3-dev 
          - python3-pip
          - python3-setuptools
          - flameshot

    - name: Pip Packages
      pip: 
        name: "{{item}}"
      loop:
        - thefuck


    - name: Home Folders
      file:
        path: "{{item}}"
        state: directory
      loop:
        - "~/code"
        - "~/dev"

    - name: Download Polybar
      git:
        repo: 'https://github.com/polybar/polybar'
        dest: ~/dev/polybar
        version: master

    - name: Build Polybar
      shell: 
        chdir: ~/dev/polybar
        cmd: |  
          mkdir build
          cd build
          cmake DCMAKE_CXX_COMPILER="clang++" ..
          make -j$(nproc)
          # Optional. This will install the polybar executable in /usr/local/bin
          sudo make install

    - name: Download Dotfiles
      git:
        repo: 'https://github.com/kumorikarasu/dotfiles.git'
        dest: ~/dotfiles
        version: linux

    - name: Set Shell
      become: yes
      user: 
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Run Dotfiles
      script:
        cmd: ~/dotfiles/setup_env.sh


