# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - ./setup_env.sh
  test:
    cmds:
      - docker build -f test/Dockerfile -t ubuntu-base:latest .
      - docker run -it -v $PWD:/home/kumori/dotfiles ubuntu-base:latest /bin/bash dotfiles/test/test-script.sh

